### ISSUE TITLE
ClassCastException in themed HandleView

### ISSUE THREAD

**Issue by mariotaku** [negusoft/holoaccent#11]
Seems there's some issue with themed text selection handle.

This problem happens on Japanese phones mostly.

```
java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
at android.widget.Editor$HandleView.updateDrawable(Editor.java:3148)
at android.widget.Editor$HandleView.<init>(Editor.java:3134)
at android.widget.Editor$InsertionHandleView.<init>(Editor.java:3520)
at android.widget.Editor$InsertionPointCursorController.getHandle(Editor.java:3796)
at android.widget.Editor$InsertionPointCursorController.show(Editor.java:3771)
at android.widget.Editor.onTouchUpEvent(Editor.java:1669)
at android.widget.TextView.onTouchEvent(TextView.java:7574)
at android.view.View.dispatchTouchEvent(View.java:7134)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1946)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1400)
at android.app.Activity.dispatchTouchEvent(Activity.java:2403)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1894)
at android.view.View.dispatchPointerEvent(View.java:7314)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3291)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3236)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4277)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4256)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4348)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:4903)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blurkidi** [comment]
Could you give some more context to the crash? Like what hardware, what android version. Does the crash happen with the sample app or did you implement your own?

Also, when you say that it crashes on Japanese phones, you mean that you have a Japanese locale set, right? Or do you mean the hardware itself is from this origin?

Thanks for the report.

**Comment by mariotaku** [comment]
AQUOS PHONE Xx 206SH (SBM206SH) 12  57.1%
AQUOS PHONE ZETA SH-02E (SH02E) 4   19.0%
AQUOS PHONE SERIE SHL22 (SHL22) 2   9.5%
AQUOS PHONE ZETA SH-06E (SH-06E)    1   4.8%
AQUOS PHONE SERIE SHL23 (SHL23) 1   4.8%
PANTONE 6 SoftBank 200SH (SBM200SH) 1   4.8%

OS versions are 4.2 and 4.1.

They said crash happens when trying to compose/select text. Seems that's not caused by locale, but ROM they use.

**Comment by blurkidi** [comment]
It seems like they are expecting a BitmapDrawable, and they receive a LayerDrawable. I don't know why they would do that, it the android source code they manage Drawable objects (as it is normal) so the casting works correctly.

I think I know how to fix it but it will require a change for this drawables, and maybe some impact in performance.

Just for curiosity, how did you test all this? what are the percentages? And do you know what ROM they are using? (stock aquos rom?)

**Comment by mariotaku** [comment]
Play store has data analytics for crashes. I have an idea, we can extend a
BitmapDrawable class to wrap LayerDrawable, use delegate methods.
2014-1-6 下午11:50于 "blurkidi" notifications@github.com写道：

**Comment by blurkidi** [comment]
"Play store has data analytics for crashes". I still don't understand how you got this information...

And no, extending the bitmap will not work. In order to replace the drawables at runtime, they have to be referenced from a XML drawable. Check the "implementation details" wiki page for more details:

https://github.com/negusoft/holoaccent/wiki/Implementation-Details

But there is a way to define a BitmapDrawable in XML with <bitmap>. Then, in stead of replacing the drawable, we have to "create" a bitmap programatically and pass an inputstream to it. It is also mentioned in the wiki page.

**Comment by blurkidi** [comment]
I think that this issue might be fixed in this commit: 5e0bf227b5f1650e3928b59cd96f7da15987ccec.

git checkout 5e0bf227b5f1650e3928b59cd96f7da15987ccec

I would appreciate if you could retest and give me some feedback. Thanks,

**Comment by mariotaku** [comment]
Thanks, I send a test build to Japanese users, I'll reply you soon if this get fixed.

**Comment by blurkidi** [comment]
Any news about the test? I just want to close the issue, but I prefer to do it with the confirmation that it is fixed.

**Comment by mariotaku** [comment]
Seems no error in new version, I'll upload new version to Google Play. Thanks.
